version: '2'
services:
  nginx:
      image: nginx:latest
      ports:
          - '80:80'
      volumes:
          - ${WEBAPP_STORAGE_HOME}/nginx:/etc/nginx/conf.d
          - ${WEBAPP_STORAGE_HOME}/logs/nginx:/var/log/nginx
          - ${WEBAPP_STORAGE_HOME}/wordpress:/var/www/html
      links:
          - wordpress
      restart: always
  mysql:
    image: mariadb
    ports:
        - '3306:3306'
    volumes:
        - ${WEBAPP_STORAGE_HOME}/db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    restart: always
  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
        - '9000:9000'
    volumes:
        - ${WEBAPP_STORAGE_HOME}/wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=aqwe123
    links:
        - mysql
    restart: always  
  